name: cl_st1_gelc_lmda_build
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.13
  - pip

  # GUI
  - pyside6

  # NLP
  - spacy
  - click
  - spacy-model-en_core_web_sm

  # Data and statistics
  - numpy
  - pandas
  - scipy

  # Plotting
  - matplotlib

  # Packaging
  - pyinstaller